name: apiverve_filesizeformatter
description: File Size Formatter is a tool for converting bytes to human-readable file sizes (KB, MB, GB, TB, etc.). It supports both binary (1024) and decimal (1000) standards with customizable precision.
version: 1.1.14
homepage: https://apiverve.com/marketplace/filesizeformatter?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/filesizeformatter-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
